### ISSUE TITLE
No se cumple lineamiento OAS de nombres de repo

### ISSUE THREAD

**Issue by jjvargass** [udistrital/seguridad_social_cliente#15]
se debe cumplir con los lineamientos definidos en el siguiente link:

https://github.com/udistrital/introduccion_oas/blob/master/repositorios_institucionales/lineamientos.md

**Comment by juancsr** [comment]
ss es un acrónimo de seguridad social

**Comment by juancsr** [comment]
Se actualiza el nombre del repositorio
